import type {
  GenerationProvider,
  GenerationRequest,
  GenerationPollResult,
  GenerationResult,
  ImageGenerationProvider,
  ImageGenerationRequest,
} from "../types/generation.js";

/**
 * Build a binary STL for a simple box (8 triangulated faces = 12 triangles).
 * Dimensions in mm: width × height × depth.
 * Returned as a data-URI so the worker can download it via fetch().
 */
function buildBoxStlDataUri(
  widthMm = 50,
  heightMm = 50,
  depthMm = 50
): string {
  const w = widthMm / 2;
  const h = heightMm / 2;
  const d = depthMm / 2;

  // 8 corners of the box
  const v: [number, number, number][] = [
    [-w, -h, -d], [w, -h, -d], [w, h, -d], [-w, h, -d],
    [-w, -h,  d], [w, -h,  d], [w, h,  d], [-w, h,  d],
  ];

  type V3 = [number, number, number];
  // 12 triangles (2 per face × 6 faces)
  const triangles: Array<{ n: V3; v: [V3, V3, V3] }> = [
    // -Z face
    { n: [0, 0, -1], v: [v[0]!, v[2]!, v[1]!] },
    { n: [0, 0, -1], v: [v[0]!, v[3]!, v[2]!] },
    // +Z face
    { n: [0, 0,  1], v: [v[4]!, v[5]!, v[6]!] },
    { n: [0, 0,  1], v: [v[4]!, v[6]!, v[7]!] },
    // -X face
    { n: [-1, 0, 0], v: [v[0]!, v[4]!, v[7]!] },
    { n: [-1, 0, 0], v: [v[0]!, v[7]!, v[3]!] },
    // +X face
    { n: [1,  0, 0], v: [v[1]!, v[2]!, v[6]!] },
    { n: [1,  0, 0], v: [v[1]!, v[6]!, v[5]!] },
    // -Y face
    { n: [0, -1, 0], v: [v[0]!, v[1]!, v[5]!] },
    { n: [0, -1, 0], v: [v[0]!, v[5]!, v[4]!] },
    // +Y face
    { n: [0,  1, 0], v: [v[2]!, v[3]!, v[7]!] },
    { n: [0,  1, 0], v: [v[2]!, v[7]!, v[6]!] },
  ];

  // Binary STL: 80-byte header + 4-byte count + N×50-byte triangles
  const buf = Buffer.alloc(80 + 4 + triangles.length * 50);
  buf.write("Mock box STL — generated by DPR mock provider", 0, "ascii");
  buf.writeUInt32LE(triangles.length, 80);

  let offset = 84;
  for (const tri of triangles) {
    buf.writeFloatLE(tri.n[0]!, offset);
    buf.writeFloatLE(tri.n[1]!, offset + 4);
    buf.writeFloatLE(tri.n[2]!, offset + 8);
    for (let i = 0; i < 3; i++) {
      const vert = tri.v[i]!;
      buf.writeFloatLE(vert[0], offset + 12 + i * 12);
      buf.writeFloatLE(vert[1], offset + 12 + i * 12 + 4);
      buf.writeFloatLE(vert[2], offset + 12 + i * 12 + 8);
    }
    buf.writeUInt16LE(0, offset + 48); // attribute byte count
    offset += 50;
  }

  return `data:model/stl;base64,${buf.toString("base64")}`;
}

/**
 * Mock 3D generation provider for local development and prototyping.
 * Returns a binary STL box (50mm × 50mm × 50mm) with a short simulated delay.
 * No API key required.
 */
export class MockGenerationProvider implements GenerationProvider, ImageGenerationProvider {
  readonly name = "mock";

  async createTask(request: GenerationRequest): Promise<{ providerTaskId: string }> {
    console.log(`[MockProvider] Received prompt: "${request.prompt}"`);
    const taskId = `mock-${Date.now()}`;
    return { providerTaskId: taskId };
  }

  async pollTask(providerTaskId: string): Promise<GenerationPollResult> {
    return {
      providerTaskId,
      status: "succeeded",
      progress: 100,
      modelUrl: buildBoxStlDataUri(50, 50, 50),
      thumbnailUrl: null,
      format: "stl",
    };
  }

  async waitForCompletion(
    providerTaskId: string,
    opts?: { pollIntervalMs?: number; timeoutMs?: number }
  ): Promise<GenerationResult> {
    // Simulate a brief generation delay so the polling UI flow feels real
    const delay = Math.min(opts?.pollIntervalMs ?? 2000, 3000);
    await new Promise((res) => setTimeout(res, delay));

    return {
      providerTaskId,
      status: "succeeded",
      modelUrl: buildBoxStlDataUri(50, 50, 50),
      thumbnailUrl: null,
      format: "stl",
    };
  }

  // ---- Image-to-3D mock methods ----

  async createImageTask(request: ImageGenerationRequest): Promise<{ providerTaskId: string }> {
    console.log(`[MockProvider] Received image-to-3D request: "${request.imageUrl}"`);
    const taskId = `mock-img-${Date.now()}`;
    return { providerTaskId: taskId };
  }

  async pollImageTask(providerTaskId: string): Promise<GenerationPollResult> {
    return {
      providerTaskId,
      status: "succeeded",
      progress: 100,
      modelUrl: buildBoxStlDataUri(50, 50, 50),
      thumbnailUrl: null,
      format: "stl",
    };
  }

  async waitForImageCompletion(
    providerTaskId: string,
    opts?: { pollIntervalMs?: number; timeoutMs?: number }
  ): Promise<GenerationResult> {
    const delay = Math.min(opts?.pollIntervalMs ?? 2000, 3000);
    await new Promise((res) => setTimeout(res, delay));

    return {
      providerTaskId,
      status: "succeeded",
      modelUrl: buildBoxStlDataUri(50, 50, 50),
      thumbnailUrl: null,
      format: "stl",
    };
  }
}
